package com.wsf.model;

public class TCatalog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_catalog.cata_id
     *
     * @mbggenerated Sat Feb 23 16:55:08 CST 2019
     */
    private Integer cataId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_catalog.cata_name
     *
     * @mbggenerated Sat Feb 23 16:55:08 CST 2019
     */
    private String cataName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_catalog.cata_desc
     *
     * @mbggenerated Sat Feb 23 16:55:08 CST 2019
     */
    private String cataDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_catalog.cata_parent
     *
     * @mbggenerated Sat Feb 23 16:55:08 CST 2019
     */
    private Integer cataParent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_catalog.cata_id
     *
     * @return the value of t_catalog.cata_id
     *
     * @mbggenerated Sat Feb 23 16:55:08 CST 2019
     */
    public Integer getCataId() {
        return cataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_catalog.cata_id
     *
     * @param cataId the value for t_catalog.cata_id
     *
     * @mbggenerated Sat Feb 23 16:55:08 CST 2019
     */
    public void setCataId(Integer cataId) {
        this.cataId = cataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_catalog.cata_name
     *
     * @return the value of t_catalog.cata_name
     *
     * @mbggenerated Sat Feb 23 16:55:08 CST 2019
     */
    public String getCataName() {
        return cataName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_catalog.cata_name
     *
     * @param cataName the value for t_catalog.cata_name
     *
     * @mbggenerated Sat Feb 23 16:55:08 CST 2019
     */
    public void setCataName(String cataName) {
        this.cataName = cataName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_catalog.cata_desc
     *
     * @return the value of t_catalog.cata_desc
     *
     * @mbggenerated Sat Feb 23 16:55:08 CST 2019
     */
    public String getCataDesc() {
        return cataDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_catalog.cata_desc
     *
     * @param cataDesc the value for t_catalog.cata_desc
     *
     * @mbggenerated Sat Feb 23 16:55:08 CST 2019
     */
    public void setCataDesc(String cataDesc) {
        this.cataDesc = cataDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_catalog.cata_parent
     *
     * @return the value of t_catalog.cata_parent
     *
     * @mbggenerated Sat Feb 23 16:55:08 CST 2019
     */
    public Integer getCataParent() {
        return cataParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_catalog.cata_parent
     *
     * @param cataParent the value for t_catalog.cata_parent
     *
     * @mbggenerated Sat Feb 23 16:55:08 CST 2019
     */
    public void setCataParent(Integer cataParent) {
        this.cataParent = cataParent;
    }

    @Override
    public String toString() {
        return "TCatalog{" +
                "cataId=" + cataId +
                ", cataName='" + cataName + '\'' +
                ", cataDesc='" + cataDesc + '\'' +
                ", cataParent=" + cataParent +
                '}';
    }
}