package com.wsf.model;

public class TDept {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.dept_no
     *
     * @mbggenerated Fri Feb 22 19:21:05 CST 2019
     */
    private Integer deptNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.dept_name
     *
     * @mbggenerated Fri Feb 22 19:21:05 CST 2019
     */
    private String deptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_dept.dept_tel
     *
     * @mbggenerated Fri Feb 22 19:21:05 CST 2019
     */
    private String deptTel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.dept_no
     *
     * @return the value of t_dept.dept_no
     *
     * @mbggenerated Fri Feb 22 19:21:05 CST 2019
     */
    public Integer getDeptNo() {
        return deptNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.dept_no
     *
     * @param deptNo the value for t_dept.dept_no
     *
     * @mbggenerated Fri Feb 22 19:21:05 CST 2019
     */
    public void setDeptNo(Integer deptNo) {
        this.deptNo = deptNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.dept_name
     *
     * @return the value of t_dept.dept_name
     *
     * @mbggenerated Fri Feb 22 19:21:05 CST 2019
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.dept_name
     *
     * @param deptName the value for t_dept.dept_name
     *
     * @mbggenerated Fri Feb 22 19:21:05 CST 2019
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_dept.dept_tel
     *
     * @return the value of t_dept.dept_tel
     *
     * @mbggenerated Fri Feb 22 19:21:05 CST 2019
     */
    public String getDeptTel() {
        return deptTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_dept.dept_tel
     *
     * @param deptTel the value for t_dept.dept_tel
     *
     * @mbggenerated Fri Feb 22 19:21:05 CST 2019
     */
    public void setDeptTel(String deptTel) {
        this.deptTel = deptTel;
    }
}