package com.wsf.model;

public class TLose {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lose.lose_id
     *
     * @mbggenerated Fri Mar 01 20:04:03 CST 2019
     */
    private Integer loseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lose.stu_id
     *
     * @mbggenerated Fri Mar 01 20:04:03 CST 2019
     */
    private Integer stuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lose.book_id
     *
     * @mbggenerated Fri Mar 01 20:04:03 CST 2019
     */
    private Integer bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lose.cause
     *
     * @mbggenerated Fri Mar 01 20:04:03 CST 2019
     */
    private String cause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_lose.is_deal
     *
     * @mbggenerated Fri Mar 01 20:04:03 CST 2019
     */
    private Integer isDeal;


    private String bookNo;
    private String bookName;
    private String bookAuthor;
    private String stuNo;
    private String stuName;

    public String getBookNo() {
        return bookNo;
    }

    public void setBookNo(String bookNo) {
        this.bookNo = bookNo;
    }

    public String getBookName() {
        return bookName;
    }

    public void setBookName(String bookName) {
        this.bookName = bookName;
    }

    public String getBookAuthor() {
        return bookAuthor;
    }

    public void setBookAuthor(String bookAuthor) {
        this.bookAuthor = bookAuthor;
    }

    public String getStuNo() {
        return stuNo;
    }

    public void setStuNo(String stuNo) {
        this.stuNo = stuNo;
    }

    public String getStuName() {
        return stuName;
    }

    public void setStuName(String stuName) {
        this.stuName = stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lose.lose_id
     *
     * @return the value of t_lose.lose_id
     *
     * @mbggenerated Fri Mar 01 20:04:03 CST 2019
     */
    public Integer getLoseId() {
        return loseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lose.lose_id
     *
     * @param loseId the value for t_lose.lose_id
     *
     * @mbggenerated Fri Mar 01 20:04:03 CST 2019
     */
    public void setLoseId(Integer loseId) {
        this.loseId = loseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lose.stu_id
     *
     * @return the value of t_lose.stu_id
     *
     * @mbggenerated Fri Mar 01 20:04:03 CST 2019
     */
    public Integer getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lose.stu_id
     *
     * @param stuId the value for t_lose.stu_id
     *
     * @mbggenerated Fri Mar 01 20:04:03 CST 2019
     */
    public void setStuId(Integer stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lose.book_id
     *
     * @return the value of t_lose.book_id
     *
     * @mbggenerated Fri Mar 01 20:04:03 CST 2019
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lose.book_id
     *
     * @param bookId the value for t_lose.book_id
     *
     * @mbggenerated Fri Mar 01 20:04:03 CST 2019
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lose.cause
     *
     * @return the value of t_lose.cause
     *
     * @mbggenerated Fri Mar 01 20:04:03 CST 2019
     */
    public String getCause() {
        return cause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lose.cause
     *
     * @param cause the value for t_lose.cause
     *
     * @mbggenerated Fri Mar 01 20:04:03 CST 2019
     */
    public void setCause(String cause) {
        this.cause = cause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_lose.is_deal
     *
     * @return the value of t_lose.is_deal
     *
     * @mbggenerated Fri Mar 01 20:04:03 CST 2019
     */
    public Integer getIsDeal() {
        return isDeal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_lose.is_deal
     *
     * @param isDeal the value for t_lose.is_deal
     *
     * @mbggenerated Fri Mar 01 20:04:03 CST 2019
     */
    public void setIsDeal(Integer isDeal) {
        this.isDeal = isDeal;
    }
}