package com.wsf.model;

public class TSpecialty {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_specialty.spec_id
     *
     * @mbggenerated Fri Feb 22 19:22:41 CST 2019
     */
    private Integer specId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_specialty.spec_name
     *
     * @mbggenerated Fri Feb 22 19:22:41 CST 2019
     */
    private String specName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_specialty.dept_no
     *
     * @mbggenerated Fri Feb 22 19:22:41 CST 2019
     */
    private Integer deptNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_specialty.spec_id
     *
     * @return the value of t_specialty.spec_id
     *
     * @mbggenerated Fri Feb 22 19:22:41 CST 2019
     */
    public Integer getSpecId() {
        return specId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_specialty.spec_id
     *
     * @param specId the value for t_specialty.spec_id
     *
     * @mbggenerated Fri Feb 22 19:22:41 CST 2019
     */
    public void setSpecId(Integer specId) {
        this.specId = specId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_specialty.spec_name
     *
     * @return the value of t_specialty.spec_name
     *
     * @mbggenerated Fri Feb 22 19:22:41 CST 2019
     */
    public String getSpecName() {
        return specName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_specialty.spec_name
     *
     * @param specName the value for t_specialty.spec_name
     *
     * @mbggenerated Fri Feb 22 19:22:41 CST 2019
     */
    public void setSpecName(String specName) {
        this.specName = specName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_specialty.dept_no
     *
     * @return the value of t_specialty.dept_no
     *
     * @mbggenerated Fri Feb 22 19:22:41 CST 2019
     */
    public Integer getDeptNo() {
        return deptNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_specialty.dept_no
     *
     * @param deptNo the value for t_specialty.dept_no
     *
     * @mbggenerated Fri Feb 22 19:22:41 CST 2019
     */
    public void setDeptNo(Integer deptNo) {
        this.deptNo = deptNo;
    }
}