package com.wsf.model;

public class TStudent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.stu_id
     *
     * @mbggenerated Fri Feb 22 19:34:16 CST 2019
     */
    private Integer stuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.dept_no
     *
     * @mbggenerated Fri Feb 22 19:34:16 CST 2019
     */
    private Integer deptNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.stu_no
     *
     * @mbggenerated Fri Feb 22 19:34:16 CST 2019
     */
    private String stuNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.stu_name
     *
     * @mbggenerated Fri Feb 22 19:34:16 CST 2019
     */
    private String stuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.stu_grade
     *
     * @mbggenerated Fri Feb 22 19:34:16 CST 2019
     */
    private Integer stuGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.stu_tel
     *
     * @mbggenerated Fri Feb 22 19:34:16 CST 2019
     */
    private String stuTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.spec_id
     *
     * @mbggenerated Fri Feb 22 19:34:16 CST 2019
     */
    private Integer specId;

    private String deptName;
    private String specName;

    public String getDeptName() {
        return deptName;
    }

    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

    public String getSpecName() {
        return specName;
    }

    public void setSpecName(String specName) {
        this.specName = specName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.stu_id
     *
     * @return the value of t_student.stu_id
     *
     * @mbggenerated Fri Feb 22 19:34:16 CST 2019
     */
    public Integer getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.stu_id
     *
     * @param stuId the value for t_student.stu_id
     *
     * @mbggenerated Fri Feb 22 19:34:16 CST 2019
     */
    public void setStuId(Integer stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.dept_no
     *
     * @return the value of t_student.dept_no
     *
     * @mbggenerated Fri Feb 22 19:34:16 CST 2019
     */
    public Integer getDeptNo() {
        return deptNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.dept_no
     *
     * @param deptNo the value for t_student.dept_no
     *
     * @mbggenerated Fri Feb 22 19:34:16 CST 2019
     */
    public void setDeptNo(Integer deptNo) {
        this.deptNo = deptNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.stu_no
     *
     * @return the value of t_student.stu_no
     *
     * @mbggenerated Fri Feb 22 19:34:16 CST 2019
     */
    public String getStuNo() {
        return stuNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.stu_no
     *
     * @param stuNo the value for t_student.stu_no
     *
     * @mbggenerated Fri Feb 22 19:34:16 CST 2019
     */
    public void setStuNo(String stuNo) {
        this.stuNo = stuNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.stu_name
     *
     * @return the value of t_student.stu_name
     *
     * @mbggenerated Fri Feb 22 19:34:16 CST 2019
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.stu_name
     *
     * @param stuName the value for t_student.stu_name
     *
     * @mbggenerated Fri Feb 22 19:34:16 CST 2019
     */
    public void setStuName(String stuName) {
        this.stuName = stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.stu_grade
     *
     * @return the value of t_student.stu_grade
     *
     * @mbggenerated Fri Feb 22 19:34:16 CST 2019
     */
    public Integer getStuGrade() {
        return stuGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.stu_grade
     *
     * @param stuGrade the value for t_student.stu_grade
     *
     * @mbggenerated Fri Feb 22 19:34:16 CST 2019
     */
    public void setStuGrade(Integer stuGrade) {
        this.stuGrade = stuGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.stu_tel
     *
     * @return the value of t_student.stu_tel
     *
     * @mbggenerated Fri Feb 22 19:34:16 CST 2019
     */
    public String getStuTel() {
        return stuTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.stu_tel
     *
     * @param stuTel the value for t_student.stu_tel
     *
     * @mbggenerated Fri Feb 22 19:34:16 CST 2019
     */
    public void setStuTel(String stuTel) {
        this.stuTel = stuTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.spec_id
     *
     * @return the value of t_student.spec_id
     *
     * @mbggenerated Fri Feb 22 19:34:16 CST 2019
     */
    public Integer getSpecId() {
        return specId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.spec_id
     *
     * @param specId the value for t_student.spec_id
     *
     * @mbggenerated Fri Feb 22 19:34:16 CST 2019
     */
    public void setSpecId(Integer specId) {
        this.specId = specId;
    }
}